"""
citation.py -- Phase 2. answer_contract.md 2's four-layer evidence citation chain, resolved
mechanically rather than asserted in prose.

    Answer number
       -> metric_id (semantic_metric_registry.csv)
          -> source_objects (tables/views actually queried)
             -> file_manifest.csv key (which exported CSV, e.g. F.001, T.journal_entries)
                -> validation_reference (the specific check that confirmed this metric's
                   reconstruction logic)

2 also fixes the crucial property this module must preserve: "A citation is not a footnote
appended after the fact -- it is generated by the same Execution step that produced the number,
since the Execution Engine only ever reads from named, manifest-resolved evidence sources; there
is no code path that could produce a number without this chain already attached."

Accordingly: an object this module cannot resolve to a manifest key is reported as UNRESOLVED
with the reason, never silently dropped. A dropped citation would make an uncited number look
cited -- ai_evaluation_framework.md 1.4 calls that a defect "regardless of whether the number
happens to be correct."
"""
import re
from dataclasses import dataclass
from functools import lru_cache


@dataclass(frozen=True)
class Citation:
    object_name: str        # the table/view as the metric names it
    manifest_key: str       # F.001 / T.journal_lines / H.056 / M.xxx, or "UNRESOLVED"
    file: str               # the exported CSV filename
    rows: str
    object_class: str       # base_table / view / diagnostic / metadata
    note: str = ""

    @property
    def resolved(self):
        return self.manifest_key != "UNRESOLVED"

    def __str__(self):
        if not self.resolved:
            return f"{self.object_name} (UNRESOLVED: {self.note})"
        return f"{self.object_name} [{self.manifest_key}, {self.file}, {self.rows} rows]"


@lru_cache(maxsize=1)
def _manifest_lookup():
    """Two indexes over file_manifest.csv: by key, and by bare logical object name."""
    from engine.evidence_loader import manifest
    df = manifest()
    by_key, by_name = {}, {}
    for _, r in df.iterrows():
        rec = {
            "key": str(r.get("key", "")),
            "logical_name": str(r.get("logical_name", "")),
            "class": str(r.get("class", "")),
            "rows": str(r.get("rows", "")),
            "file": str(r.get("file", "")),
        }
        by_key[rec["key"]] = rec
        bare = rec["logical_name"].split(".")[-1].strip().lower()
        if bare:
            by_name.setdefault(bare, rec)
        # Functions are exported as key "FN.<name>" with logical_name "fn__<name>" -- index
        # them under their real callable name so a metric citing get_occupancy_intelligence
        # resolves to FN.get_occupancy_intelligence.
        if rec["key"].startswith("FN.") and "." in rec["key"]:
            by_name.setdefault(rec["key"].split(".", 1)[1].strip().lower(), rec)
        if bare.startswith("fn__"):
            by_name.setdefault(bare[4:], rec)
        # Diagnostic exports (H.*) record the view's name WITHOUT its leading "v_"
        # (H.001 = "je_amount_reconciliation" is the export of v_je_amount_reconciliation),
        # while the semantic registry cites the real view name. Index the v_-prefixed form so
        # that citation resolves. This is a mechanical prefix alias only -- no fuzzy matching:
        # a registry name that merely RESEMBLES a manifest entry (v_diag_deposit_phantom vs
        # H.045 deposit_phantom_rows) stays UNRESOLVED rather than being guessed at.
        if rec["key"].startswith("H.") and bare and not bare.startswith("v_"):
            by_name.setdefault(f"v_{bare}", rec)
    return by_key, by_name


# Matches a manifest key embedded in the registry text, parenthesised ("v_pnl (F.001)") or
# bare ("Same as M.AR.001A-D; F.006, F.007"). Both forms occur in semantic_metric_registry.csv.
_EXPLICIT_KEY = re.compile(r"\(([FTH]\.[A-Za-z0-9_]+)\)")
_BARE_KEY = re.compile(r"^([FTH]\.[A-Za-z0-9_]+)$")

# "Def A: journal_lines/journal_entries" -- a per-definition prefix, not part of the name.
_DEF_PREFIX = re.compile(r"^(Def(inition)?\s+[A-Za-z0-9]+\s*:)\s*", re.IGNORECASE)
# "tenant_allotments (+ beds/apartments for availability window)" -- an explanatory aside.
_TRAILING_PAREN = re.compile(r"\s*\([^)]*\)\s*$")


# A candidate evidence-object token: a manifest key (F.001, T.receipts, FN.get_universal_metrics,
# H.056) or a SQL identifier (journal_lines, v_pnl, get_occupancy_intelligence).
_TOKEN = re.compile(r"\b((?:[FTHM]|FN)\.[A-Za-z0-9_]+|[A-Za-z][A-Za-z0-9_]*)\b")

# Prose words that appear inside `source_objects` but are not object names. Anything not
# matching an object-shaped pattern AND not resolving against the manifest is treated as prose
# and counted (never silently vanished -- the count is reported on the chain).
def _looks_like_object(tok):
    return ("_" in tok) or ("." in tok) or tok.lower().startswith(("v_", "get_", "fn_", "trg_"))


def _split_objects(source_objects):
    """`source_objects` is free prose. Across the 49 registry rows it mixes semicolon clauses,
    comma lists, slash alternatives, sentence periods, per-definition `Def A:` prefixes,
    parenthesised manifest keys, and parenthesised explanatory asides -- there is no single
    separator to split on reliably.

    So rather than chase separators, extract every *token* that is shaped like a database object
    or a manifest key. This is robust to any prose arrangement, and its failure mode is safe:
    a token that is not a real object simply fails to resolve and is reported, never invented.
    """
    text = source_objects or ""
    seen, out = set(), []
    for m in _TOKEN.finditer(text):
        tok = m.group(1)
        if tok.lower() in seen:
            continue
        seen.add(tok.lower())
        out.append(tok)
    return out


def cite_objects(source_objects):
    """Resolve every object a metric declares into a Citation.

    Returns (citations, n_prose_tokens_skipped). A token that neither resolves against
    file_manifest.csv nor *looks* like a database object is ordinary prose ("both", "bodies",
    "exported") -- it is counted and reported, not emitted as a bogus UNRESOLVED citation and
    not silently discarded.
    """
    by_key, by_name = _manifest_lookup()
    by_logical = {v["logical_name"].lower(): v for v in by_key.values()}
    out, seen, prose_skipped = [], set(), 0

    for tok in _split_objects(source_objects):
        low = tok.lower()
        rec = by_key.get(tok) or by_name.get(low) or by_logical.get(f"public.{low}")

        if rec is None:
            if not _looks_like_object(tok):
                prose_skipped += 1
                continue
            rec_note = ("No exported object of this name appears in file_manifest.csv "
                        "(it may be a function referenced only by name, a non-exported view, "
                        "or -- for this project's own deliverables -- not evidence at all).")
            cit = Citation(object_name=tok, manifest_key="UNRESOLVED", file="", rows="",
                           object_class="", note=rec_note)
        else:
            cit = Citation(object_name=tok, manifest_key=rec["key"], file=rec["file"],
                           rows=rec["rows"], object_class=rec["class"])

        if cit.manifest_key in seen and cit.resolved:
            continue
        if cit.resolved:
            seen.add(cit.manifest_key)
        out.append(cit)

    return tuple(out), prose_skipped


@dataclass(frozen=True)
class CitationChain:
    """The full four-layer chain for one metric, as answer_contract.md 2 specifies it."""
    metric_id: str
    citations: tuple
    validation_reference: str
    prose_tokens_skipped: int = 0

    @property
    def resolved_keys(self):
        return tuple(c.manifest_key for c in self.citations if c.resolved)

    @property
    def unresolved(self):
        return tuple(c for c in self.citations if not c.resolved)

    @property
    def complete(self):
        """A chain is complete when at least one evidence object resolved to a manifest key.
        A metric citing only unresolvable objects cannot ground a number."""
        return len(self.resolved_keys) > 0

    def render(self):
        """answer_contract.md 2's format guidance: 'a citation should let a technically-literate
        reviewer find the exact evidence file and re-run the check.' Not a rigid template."""
        parts = [f"{self.metric_id}"]
        if self.citations:
            parts.append("evidence: " + "; ".join(str(c) for c in self.citations))
        if self.validation_reference:
            parts.append(f"validated: {self.validation_reference}")
        return " | ".join(parts)


def chain_for(spec) -> CitationChain:
    citations, prose_skipped = cite_objects(spec.source_objects)
    return CitationChain(
        metric_id=spec.metric_id,
        citations=citations,
        validation_reference=spec.validation_reference,
        prose_tokens_skipped=prose_skipped,
    )
