"""
explainability.py -- Phase 6. "Why are you saying this?"

The owner must be able to take any statement the system made and walk back to the evidence:

    Question -> interpretation -> analyst role -> metric -> calculation -> source evidence
             -> validation -> trust decision -> reasoning -> recommendation

Nothing here computes anything. Every link is READ from an object an earlier stage already
produced, which is the point: if a link cannot be filled, that is a real gap in the chain and
the chain says so rather than narrating over it. answer_contract.md 2 makes the same point about
citations -- "A citation is not a footnote appended after the fact -- it is generated by the
same Execution step that produced the number" -- and this module is that principle applied to
the whole pipeline instead of to one figure.
"""
import re
from dataclasses import dataclass, field

from engine.result import NOT_DETERMINABLE_TEXT

# The chain's fixed links, in the order the Phase 6 brief 14 gives them.
LINK_QUESTION = "question"
LINK_INTERPRETATION = "interpretation"
LINK_ANALYST_ROLE = "analyst_role"
LINK_METRIC = "metric"
LINK_CALCULATION = "calculation"
LINK_EVIDENCE = "source_evidence"
LINK_VALIDATION = "validation"
LINK_TRUST = "trust_decision"
LINK_REASONING = "reasoning"
LINK_RECOMMENDATION = "recommendation"

ALL_LINKS = (LINK_QUESTION, LINK_INTERPRETATION, LINK_ANALYST_ROLE, LINK_METRIC,
             LINK_CALCULATION, LINK_EVIDENCE, LINK_VALIDATION, LINK_TRUST, LINK_REASONING,
             LINK_RECOMMENDATION)

# Links that are legitimately empty for some answers, with the condition under which that is so.
# A link outside this map that comes back empty is a defect, not a variation.
CONDITIONALLY_EMPTY = {
    LINK_RECOMMENDATION: "only present when the question asked for one, or an insight carried "
                         "one (business_reasoning_spec.md 3's ceiling table)",
    LINK_REASONING: "only present once a CALCULATION exists to reason about",
    LINK_CALCULATION: "absent when the question terminated before execution "
                      "(clarification, refusal, or a structural limitation)",
    LINK_EVIDENCE: "absent when nothing was computed",
    LINK_VALIDATION: "absent when nothing was computed",
    LINK_METRIC: "absent when no metric resolved",
}


@dataclass(frozen=True)
class ChainLink:
    name: str
    content: str
    source: str = ""            # the module/document this link was read from
    present: bool = True


@dataclass
class EvidenceChain:
    links: tuple = ()
    complete: bool = False
    gaps: tuple = ()

    def get(self, name):
        for l in self.links:
            if l.name == name:
                return l
        return None

    def render(self):
        out = ["WHY THIS ANSWER -- evidence chain", ""]
        for l in self.links:
            marker = "  " if l.present else "  (not applicable) "
            out.append(f"{marker}{l.name.upper()}: {l.content}")
            if l.source:
                out.append(f"      source: {l.source}")
        if self.gaps:
            out.append("")
            out.append("GAPS")
            for g in self.gaps:
                out.append(f"  - {g}")
        return "\n".join(out)


def build(result, routing=None):
    """Assemble the chain from a completed AskResult (Phase 4/5) plus its role routing."""
    links, gaps = [], []

    def add(name, content, source="", present=True):
        links.append(ChainLink(name=name, content=content, source=source, present=present))

    add(LINK_QUESTION, result.question, "the owner's own words")

    interp = []
    if result.llm_request is not None:
        r = result.llm_request
        interp.append(f"intent={list(r.intent)}")
        if r.concept:
            interp.append(f"concept={r.concept}")
        if r.time_range:
            interp.append(f"period={r.time_range}")
        if r.dimensions:
            interp.append(f"dimensions={list(r.dimensions)}")
    if result.inherited_context:
        interp.append(f"inherited from the previous turn: {list(result.inherited_context)}")
    add(LINK_INTERPRETATION, "; ".join(interp) or "no structured interpretation was produced",
        "structured_output.py (the model's proposal, after contract validation)",
        present=bool(interp))

    if routing is not None:
        add(LINK_ANALYST_ROLE,
            "; ".join(routing.explain()),
            "analyst_roles.py routing over the metric's domain and the question's intent")
    else:
        add(LINK_ANALYST_ROLE, "no lens routing recorded for this turn", present=False)

    if result.metric_ids:
        add(LINK_METRIC, ", ".join(result.metric_ids), "semantic_metric_registry.csv")
    else:
        add(LINK_METRIC, "no metric resolved", present=False)
        gaps.append(f"{LINK_METRIC}: {CONDITIONALLY_EMPTY[LINK_METRIC]}")

    calc, evidence, validation = [], [], []
    for a in result.answers:
        for r in a.results:
            calc.append(f"[{r.metric_id}/{r.definition_label}] "
                        f"{r.calculation_provenance[:220]}")
            evidence.extend(str(e) for e in r.evidence_sources[:6])
            validation.append(f"{r.metric_id}: {r.validation_status}"
                              + (f" ({r.validation_reference[:120]})"
                                 if r.validation_reference else ""))

    add(LINK_CALCULATION, " | ".join(calc) or "nothing was computed",
        "analytics_execution_spec.md 3-7, applied by engine/calculators/",
        present=bool(calc))

    # Source lineage sits between evidence filenames and actual DB objects.
    # Never invent names — unresolved objects stay "Not determinable from exported evidence."
    lineage_bits = []
    if result.metric_ids:
        try:
            from engine import source_lineage as lineage_mod
            for mid in result.metric_ids[:3]:
                rec = lineage_mod.lineage_for_metric(mid)
                for ref in rec.source_objects[:4]:
                    lineage_bits.append(
                        f"{mid}:{ref.declared_name}→"
                        f"{ref.actual_source_object}"
                        f"[{ref.manifest_key}/{ref.lineage_confidence}]"
                    )
                if rec.date_basis:
                    lineage_bits.append(f"{mid}:date_basis={rec.date_basis[:80]}")
        except Exception:
            lineage_bits = []

    evidence_content = ", ".join(dict.fromkeys(evidence)) or "no evidence was read"
    if lineage_bits:
        evidence_content = evidence_content + " || lineage: " + "; ".join(lineage_bits)
    add(LINK_EVIDENCE, evidence_content,
        "evidence/file_manifest.csv + engine/source_lineage.py", present=bool(evidence) or bool(lineage_bits))
    add(LINK_VALIDATION, " | ".join(validation) or "nothing was validated",
        "validation_summary.csv (80 checks) via engine/validator.py",
        present=bool(validation))

    trust_bits = []
    if result.trust_level:
        trust_bits.append(f"trust_level={result.trust_level}")
    if result.plan is not None:
        trust_bits.append(f"headline_permitted={result.plan.headline_permitted}")
        if result.plan.trust_reason:
            trust_bits.append(result.plan.trust_reason[:200])
        if result.plan.required_disclosures:
            trust_bits.append(f"disclosures={list(result.plan.required_disclosures)}")
    add(LINK_TRUST, "; ".join(trust_bits) or "no trust verdict recorded",
        "engine/gate.py (Layer 3), ai_trust_policy.md", present=bool(trust_bits))

    reasoning = []
    if result.reasoning is not None:
        for s in result.reasoning.statements:
            reasoning.append(f"{s.stage}: {s.text[:180]}")
        if result.reasoning.ceiling_raised_for_disclosure:
            reasoning.append(
                f"(ceiling raised from {result.reasoning.intent_ceiling} to "
                f"{result.reasoning.ceiling} because a conflict disclosure is mandatory)")
    add(LINK_REASONING, " | ".join(reasoning) or "no reasoning stage ran",
        "business_reasoning_spec.md ladder via engine/business_reasoning.py",
        present=bool(reasoning))
    if not reasoning:
        gaps.append(f"{LINK_REASONING}: {CONDITIONALLY_EMPTY[LINK_REASONING]}")

    recs = []
    if result.reasoning is not None:
        recs = [s.text for s in result.reasoning.statements if s.stage == "RECOMMENDATION"]
    ds = getattr(result, "decision_support", None)
    if ds is not None and getattr(ds, "recommended_actions", ()):
        recs.extend(str(a) for a in ds.recommended_actions)
    add(LINK_RECOMMENDATION, " | ".join(recs) or "no recommendation was made",
        "business_reasoning_spec.md 2 RECOMMENDATION gating rule", present=bool(recs))
    if not recs:
        gaps.append(f"{LINK_RECOMMENDATION}: {CONDITIONALLY_EMPTY[LINK_RECOMMENDATION]}")

    for l in links:
        if not l.present and l.name not in CONDITIONALLY_EMPTY:
            gaps.append(f"{l.name}: empty, and this link has no documented empty case")

    required_present = all(
        (chain_link.present or chain_link.name in CONDITIONALLY_EMPTY)
        for chain_link in links)

    return EvidenceChain(links=tuple(links), complete=required_present, gaps=tuple(gaps))


def validate(chain: EvidenceChain):
    """Every link must be PRESENT or documented-as-conditionally-empty. Returns violations."""
    v = []
    names = [l.name for l in chain.links]
    for required in ALL_LINKS:
        if required not in names:
            v.append(f"chain is missing the {required!r} link entirely")
    for l in chain.links:
        if not l.present and l.name not in CONDITIONALLY_EMPTY:
            v.append(f"{l.name!r} is empty and has no documented empty case")
        if l.present and not l.content.strip():
            v.append(f"{l.name!r} claims to be present but carries no content")
        if l.present and l.name not in (LINK_QUESTION,) and not l.source:
            v.append(f"{l.name!r} cites no source module or document")
    return tuple(v)


# --------------------------------------------------------------------------------------------
# Owner-readable projection
# --------------------------------------------------------------------------------------------
#
# The chain above is the audit record: it names metric IDs, registry files, specification
# sections and engine modules, because an auditor needs to retrace exactly what ran. Shown to a
# business owner under "Why are you saying this?", that same record reads as machine internals
# and answers a question they did not ask.
#
# This is a PROJECTION of the identical chain -- same facts, owner's vocabulary. It adds nothing:
# every field below is copied from the chain, the registry description, or the trust verdict.
# The technical chain remains available unchanged for developer and audit views.


# Anything that identifies HOW the system is built, rather than WHAT the business measure means.
# The chain above legitimately carries all of it; this projection must carry none of it.
_INTERNAL_HANDLE = re.compile(
    r"\b(?:M|T|F|FN|H|D|DQ|C|INS|REV|EXP|COL|AR|OCC|PNL)\.[A-Za-z0-9_.]+\b")
_FILE_NAME = re.compile(r"\b[\w-]+\.(?:md|csv|py|json|sql|ya?ml)\b", re.I)
_MODULE_PATH = re.compile(r"\b(?:engine|api|frontend|tests|scripts)[/.][\w/.]+", re.I)
_DB_NAME = re.compile(
    r"\b(?:public\.[\w.]+|v_[a-z0-9_]+|vw_[a-z0-9_]+|get_[a-z0-9_]+"
    r"|[a-z][a-z0-9]*_[a-z0-9_]+\.[a-z][a-z0-9_]*)\b", re.I)
_SQL = re.compile(r"\b(?:GROUP\s+BY|ORDER\s+BY|SELECT|WHERE|SUM\(|COUNT\(|JOIN)\b", re.I)
_LAYER_TALK = re.compile(
    r"\b(?:trust\s+gate|layer\s*[123]|semantic[_ ]metric[_ ]registry|planner|executor"
    r"|metric_id|execution_call|ai_handling|plan_type|reversal-excluded|signed_amount)\b", re.I)
_DICT_LIKE = re.compile(r"[{\[]\s*['\"]?\w+['\"]?\s*[:,]")

_SCRUBBERS = (_INTERNAL_HANDLE, _FILE_NAME, _MODULE_PATH, _DB_NAME, _SQL, _LAYER_TALK,
              _DICT_LIKE)


def _is_owner_safe(text):
    """True when a sentence carries nothing that identifies the implementation."""
    return not any(p.search(text or "") for p in _SCRUBBERS)


def _clean(text):
    """Drop any sentence naming an internal thing, rather than trying to repair it.

    Deleting an identifier mid-sentence leaves wreckage ("because classifies it CRITICAL"), and
    half a sentence about internals is still about internals. The sentences this module writes
    are safe by construction; this is the backstop for text copied from elsewhere.
    """
    kept = [s.strip() for s in re.split(r"(?<=[.!?])\s+", (text or "").strip())
            if s.strip() and _is_owner_safe(s) and not _SYSTEM_DIRECTIVE.search(s)]
    return " ".join(kept)


# A registry caveat is written for the system that must obey it, not for the owner:
# "DISCLOSE: answer, but state the known limitation." names a posture and gives an instruction.
# The posture is already shown as the answer's own badge, and the instruction has been carried
# out -- the limitation IS what the panel goes on to say.
_SYSTEM_DIRECTIVE = re.compile(
    r"^\s*(?:SAFE|DISCLOSE|SHOW_BOTH|BLOCK|NOT_DETERMINABLE)\s*[:\-]"
    r"|\banswer,?\s+but\s+state\b"
    r"|\bnever\s+(?:answer|present|state)\b", re.I)


def _subject(result):
    """The measure in the owner's word -- "profit", "tenant dues" -- never an identifier."""
    concept = ""
    request = getattr(result, "llm_request", None)
    if request is not None:
        concept = getattr(request, "concept", "") or ""
    if not concept:
        plan = getattr(result, "plan", None)
        metric = getattr(plan, "metric", None) if plan is not None else None
        concept = getattr(metric, "concept", "") or ""
    concept = concept.replace("explicit:", "").replace("_", " ").strip()
    return concept or "this measure"


def _requested_period(result, change):
    """The period the OWNER asked for, in words. Empty when they asked for none."""
    from engine import owner_presentation as op
    if change is not None:
        asked = getattr(change, "requested_current", "") or ""
        against = getattr(change, "requested_previous", "") or ""
        if asked and against:
            return f"{op._month_name(asked)} compared with {op._month_name(against)}"
        if asked:
            return op._month_name(asked)
    plan = getattr(result, "plan", None)
    time = getattr(plan, "time", None) if plan is not None else None
    label = (getattr(time, "period_label", "") or "").strip()
    if label and label != "all-time":
        if re.match(r"^\d{4}-\d{2}$", label):
            return op._month_name(label + "-01")
        return label
    return ""


def _definition_count(result):
    """How many competing definitions the evidence carries for this measure."""
    labels = set()
    for a in (getattr(result, "answers", ()) or ()):
        for r in a.results:
            if r.definition_label:
                labels.add(r.definition_label)
    if labels:
        return len(labels)
    return len(getattr(result, "metric_ids", ()) or ())


_COUNT_WORDS = {2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven"}


def _definitions_phrase(count, qualifier=""):
    """"three definitions" / "more than one definition" -- grammatical either way.

    The count comes from the definitions actually returned. A terminal answer returns none, so
    the exact number is genuinely unknown there and the phrase says so instead of guessing.
    """
    word = _COUNT_WORDS.get(count)
    adjective = f" {qualifier}" if qualifier else ""
    if word:
        return f"{word} different{adjective} definitions"
    return f"more than one{adjective} definition"


def _forecast_reason(result):
    """Why a projection can be offered, in the owner's terms. Empty when this is not one.

    A forecast's trust question is not "is the figure recorded correctly" -- nothing is recorded
    for a month that has not happened. It is "how far out is this, and how wrong has the method
    been before". Both are already measured; this states them.
    """
    forecast = getattr(result, "forecast", None)
    if forecast is None or not getattr(forecast, "available", False):
        return []

    from engine import owner_presentation as op

    points = list(getattr(forecast, "points", ()) or ())
    if not points:
        return []

    if len(points) == 1:
        scope = f"for {op._month_name(points[0].period + '-01')}"
    else:
        scope = (f"for the {len(points)} months from "
                 f"{op._month_name(points[0].period + '-01')} to "
                 f"{op._month_name(points[-1].period + '-01')}")

    out = [f"This is a projection {scope}, not a recorded figure. It continues the trend in "
           f"your own revenue history; no month there has happened yet."]

    mape = (getattr(forecast, "backtest", None) or {}).get("mape_pct")
    if mape is not None:
        out.append(
            f"The method was tested by projecting months it had not been shown and comparing "
            f"against what actually happened. At this range it was off by about {mape}% on "
            f"average, which is the honest margin to read the figure with.")

    training_end = getattr(forecast, "training_end", "")
    observations = getattr(forecast, "observations", 0)
    if training_end and observations:
        out.append(
            f"It is built from {observations} complete months of trading up to "
            f"{op._month_name(training_end + '-01')}. Nothing outside your own records "
            f"contributes to it.")
    return out


def _stated_limitations(result, reason):
    """Limitations the answer already carries, when they are sentences an owner can read.

    A capability-gap answer -- an unsupported forecast, a scenario -- has no plan and no
    executed metric, so the refusal sentence was the whole of its "Why?". Its own limitations
    say the rest: which capability is missing, and what the figure shown beside the refusal
    actually is. Only full sentences are taken; a bare label is a category name, not a reason,
    and belongs nowhere near this panel.
    """
    out = []
    for limitation in (getattr(result, "limitations", ()) or ()):
        text = _clean(str(limitation))
        if not text or " " not in text.strip() or not text.rstrip().endswith("."):
            continue
        if text in reason or text in out:
            continue
        out.append(text)
    return out


def _measure_word(metric_name):
    """A measure named the way an owner says it. "Revenue by month" -> "revenue"."""
    from engine import owner_presentation as op

    text = op.owner_family_name(metric_name or "")
    text = re.sub(r"\s+by\s+(?:month|period|day)\s*$", "", text, flags=re.I).strip()
    # Only lower-cased where the word is ordinary English. "P&L" is not.
    return text if text.isupper() or not text[:1].isalpha() or "&" in text else text.lower()


def _joined(words):
    words = list(dict.fromkeys(w for w in words if w))
    if len(words) <= 1:
        return words[0] if words else ""
    return ", ".join(words[:-1]) + " and " + words[-1]


def _change_analysis_reason(result):
    """Why a change review shows what it shows, built from the movements it actually produced.

    A whole-business change review carries no trust level of its own -- each movement carries
    its own -- so it fell into the "Why I can't answer this" branch and was explained by
    restating the entire answer back at the owner, figures and headings included. That is not a
    reason; it is the answer a second time, under a heading saying it could not be given.

    What the owner is actually asking is which measures the records could be compared on, which
    could not, and why nothing is called significant. All three are already decided by the
    workflow: this reads them off the change objects rather than inventing an account of them.
    No figure is repeated -- the movements are in the answer above, and a number inside "why"
    reads as a second, differently-derived one.
    """
    from engine.change_detection import (INCREASE, DECREASE, NO_CHANGE, UNAVAILABLE,
                                         PARTIAL_PERIOD)

    changes = list(getattr(result, "changes", ()) or ())
    if not changes:
        return []

    compared, unavailable, partial = [], [], []
    for change in changes:
        name = _measure_word(getattr(change, "metric_name", ""))
        classification = getattr(change, "classification", "")
        if classification in (INCREASE, DECREASE, NO_CHANGE):
            compared.append(name)
        elif classification == PARTIAL_PERIOD:
            partial.append(name)
        elif classification == UNAVAILABLE:
            unavailable.append(name)

    paragraphs = []
    if compared:
        paragraphs.append(
            f"The records support month-to-month movements for {_joined(compared)}, so those "
            f"changes are shown directly.")
    if unavailable:
        names = _joined(unavailable)
        paragraphs.append(
            f"A comparable {names} movement is not available from the exported evidence, so no "
            f"{names} change is estimated.")
    if partial:
        paragraphs.append(
            f"The month asked about is not yet complete for {_joined(partial)}, so the figure "
            f"shown is to date rather than a whole-month comparison.")
    return paragraphs


def _descriptive_reason(result):
    """Why a descriptive summary says what it says, read off the summary it produced.

    Without this the DISCLOSE branch explained a distribution of recorded rents with "this
    measure has one agreed definition, taken from your own business records" -- true of a
    ledger total and beside the point here. What an owner wants to know about a description is
    what was described, which statistics were used, and how blanks and zeros were treated.
    """
    summary = getattr(result, "descriptive", None)
    if summary is None or not getattr(summary, "available", False):
        return []

    stats = getattr(summary, "stats", None) or {}
    label = (getattr(summary, "label", "") or "").strip()
    source = (getattr(summary, "source", "") or "the recorded values").strip()
    subject = label[:1].lower() + label[1:] if label else "these values"

    out = [f"This describes {subject} as recorded in {source} -- every value counted, none "
           f"selected or adjusted."]

    used = []
    if stats.get("median") is not None:
        used.append("the typical value")
    if stats.get("p25") is not None and stats.get("p75") is not None:
        used.append("the range the middle half sit in")
    if stats.get("min") is not None and stats.get("max") is not None:
        used.append("the full recorded span")
    if used:
        out.append(f"It reports {_joined(used)}: the descriptions the number of records "
                   f"supports, and no statistic beyond them.")

    handling = []
    if stats.get("missing_count"):
        handling.append("records with nothing entered are counted and reported separately "
                        "rather than treated as zero")
    if stats.get("zero_count"):
        handling.append("values entered as zero are kept as recorded")
    if handling:
        out.append(f"Following the evidence, {_joined(handling)}.")
    return out


_SHOWN_DIRECTLY = ("Measures the records agree on are shown directly, each with any caveat its "
                   "own evidence carries.")
_NOT_COLLAPSED = ("Measures whose records hold competing definitions are shown per definition "
                  "rather than collapsed into one figure. Choosing between them is a business "
                  "decision, so it is left to you rather than settled here.")


def _workflow_reason(result):
    """How a whole-business workflow assembled its answer, from what it actually produced.

    These answers span many measures with their own postures, so `trust_level` is empty and
    every posture branch misreads them. A briefing was being headed "Why I can't answer this"
    and explained by pasting the entire briefing back -- every figure, the takeaway included.

    Each workflow is explained by its own shape rather than by its content: what a briefing
    does with agreement and disagreement, what the attention queue does and deliberately does
    not do, what the trust review preserves. No figure is repeated; they are in the answer.
    """
    intent = (getattr(result, "owner_intent", "") or "").strip()
    summary = getattr(result, "summary", None)
    sections = summary.sections().values() if hasattr(summary, "sections") else ()
    lines = [ln for section in sections for ln in (section or ())]
    postures = {(getattr(ln, "trust_level", "") or "").upper() for ln in lines}

    if intent == "what_to_do":
        paragraphs = [
            "This is the queue of things the records cannot settle on their own -- each one "
            "needs a decision only you can make.",
            "They are listed rather than ranked: no priority score exists in the evidence, and "
            "inventing one would put an ordering on your decisions that nothing supports."]
        if postures & {"SHOW_BOTH", "BLOCK"}:
            paragraphs.append(_NOT_COLLAPSED)
        return paragraphs

    if intent == "what_to_trust":
        return [
            "This groups the measures by the reliability their own evidence already carries.",
            "Nothing here is upgraded or downgraded: each measure keeps the posture the "
            "records assigned it, and the grouping only makes that visible in one place."]

    if not lines:
        return []

    paragraphs = [
        "This is a snapshot built from the evidence as exported, not a live feed: every figure "
        "in it comes from the same records, read at the same moment."]
    if postures & {"SAFE", "DISCLOSE"}:
        paragraphs.append(_SHOWN_DIRECTLY)
    if postures & {"SHOW_BOTH", "BLOCK"}:
        paragraphs.append(_NOT_COLLAPSED)
    if getattr(summary, "attention_required", ()):
        paragraphs.append(
            "Items that need your decision are surfaced as their own list rather than resolved "
            "quietly inside the numbers.")
    if getattr(summary, "what_changed", ()):
        paragraphs.append(
            "Period movements the records can support are included; the ones they cannot are "
            "named as unavailable rather than left out.")
    return paragraphs


def _clarification_reason(result):
    """Why a question was answered with a question. Nothing was refused and nothing computed.

    A pending clarification is not a limitation. It was being explained under "Why I can't
    answer this", with the clarification itself dumped in as the reason -- which told the owner
    their question had failed, when what actually happened is that the records hold more than
    one valid answer and the system declined to pick one for them.
    """
    clarification = getattr(result, "clarification", None)
    if clarification is None:
        return []

    count = len(getattr(clarification, "options", ()) or ())
    subject = _subject(result)
    if subject == "this measure":
        # A clarification turn has no plan and no model proposal to read the subject from, but
        # the clarification itself remembers the question that triggered it.
        from engine import concept_map

        original = getattr(clarification, "original_question", "") or ""
        matched = concept_map.match(original)
        if matched:
            subject = matched[0][0].name.replace("_", " ")
    if count < 2:
        return [f"This question needs one clarification before it can be answered, so that the "
                f"figure returned is the one you meant."]
    return [
        f"This question needs one clarification because the records contain "
        f"{_number_word(count)} valid definitions of {subject}. I won't choose between them on "
        f"your behalf.",
        "They are not versions of one figure with a right answer between them -- each is "
        "supported by its own evidence and produces a different total. Once you pick one, the "
        "question you asked runs against it unchanged."]


_NUMBER_WORDS = {2: "two", 3: "three", 4: "four", 5: "five", 6: "six"}


def _number_word(n):
    return _NUMBER_WORDS.get(n, str(n))


def _forecast_refusal_reason(result):
    """Why a forecast was declined, said as a limit of the method rather than of the records.

    A refused forecast used to be explained with the coverage sentence -- "that period isn't
    fully covered by the exported data" -- which is the wrong reason twice over: the records
    will never cover a future month, and the actual limit is how far the method has been
    validated. This states that limit, and that the system declines rather than extrapolating
    past it.
    """
    forecast = getattr(result, "forecast", None)
    if forecast is None or getattr(forecast, "available", True):
        return []

    from engine.forecasting import MAX_HORIZON

    return [f"This is a limit of the forecasting method, not of your records. It has been "
            f"tested only as far as {MAX_HORIZON} months ahead, and beyond that its accuracy "
            f"has not been measured -- so no figure is offered rather than one that cannot be "
            f"stood behind."]


def owner_projection(result, chain=None, registry=None, change=None, trust_level=None):
    """The owner-facing "Why?" -- a narrative, not a field dump.

    Same facts as the evidence chain, told as the business reason rather than the mechanism.
    Which story gets told is chosen by the TRUST POSTURE the gate already returned, because
    that is precisely what the owner is asking: can I rely on this, and if not, why not.

    Returns {"heading": str, "paragraphs": [str, ...]}. Nothing here recomputes, re-judges or
    softens anything -- a posture this function does not recognise yields no projection rather
    than a guess.
    """
    # The OWNER-facing posture wins where the caller has one. A metric answer can be
    # narrowed after execution -- a comparison that could not be produced ends
    # NOT_DETERMINABLE even though the metric it ran against is DISCLOSE -- and reading
    # the pre-narrowing level headed a refusal "Why this answer is trusted".
    trust = ((trust_level if trust_level is not None
              else getattr(result, "trust_level", "")) or "").upper()
    subject = _subject(result)
    period = _requested_period(result, change)
    paragraphs = []

    # Workflow answers first. Each of these is assembled from several measures with their own
    # postures, so `trust_level` is empty and every branch below would misread it -- a briefing
    # and a change review were both being headed "Why I can't answer this" and explained by
    # pasting the answer back. They are dispatched on what the workflow actually produced.
    # A pending clarification comes first: the question has not been answered yet, so no
    # posture below applies and neither does any workflow's account of what it produced.
    clarification_reasons = _clarification_reason(result)
    if clarification_reasons:
        cleaned = [p for p in (_clean(x) for x in clarification_reasons) if p]
        if cleaned:
            return {"heading": "Why I need one answer from you", "paragraphs": cleaned}

    for build in (_change_analysis_reason, _workflow_reason, _descriptive_reason):
        reasons = build(result)
        if not reasons:
            continue
        paragraphs = reasons + _stated_limitations(result, " ".join(reasons))
        cleaned = [p for p in (_clean(x) for x in paragraphs) if p]
        if cleaned:
            return {"heading": "Why this answer is shown", "paragraphs": cleaned}

    if trust == "BLOCK":
        heading = "Why this answer is blocked"
        how_many = _definitions_phrase(_definition_count(result))
        paragraphs.append(
            f"The records contain {how_many} of {subject}, and they do not agree. "
            f"Because the difference cannot be resolved from the available evidence, I won't "
            f"choose one as the official {subject} figure.")
        if period:
            paragraphs.append(
                f"You also asked for {period}. The competing {subject} definitions have no "
                f"reliable month-by-month series in this export, so that period cannot be "
                f"isolated either.")
        paragraphs.append(
            f"Decision needed: management must decide which {subject} definition should be "
            f"treated as the official business definition.")

    elif trust == "SHOW_BOTH":
        heading = "Why multiple figures are shown"
        how_many = _definitions_phrase(_definition_count(result), qualifier="evidence-backed")
        paragraphs.append(
            f"The records contain {how_many} of {subject}. "
            f"They produce materially different totals, so I have shown all of "
            f"them rather than selecting one without a business decision.")
        if period:
            paragraphs.append(f"The period you asked about was {period}.")
        paragraphs.append(
            "Choosing between them is a business decision, not something the evidence settles.")

    elif trust in ("SAFE", "DISCLOSE"):
        heading = "Why this answer is trusted"
        forecast_paragraphs = _forecast_reason(result)
        if forecast_paragraphs:
            # A projection is not a recorded figure, and saying it was "taken from your own
            # business records" answers the owner's question wrongly: they are asking whether
            # they can rely on a number for a month that has not happened yet.
            heading = "Why this projection is offered"
            paragraphs.extend(forecast_paragraphs)
        else:
            checked = any((r.validation_status or "").upper() == "MATCH"
                          for a in (getattr(result, "answers", ()) or ()) for r in a.results)
            chosen = (getattr(result, "clarification_state", "") or "").upper() == "ANSWERED"
            if chosen:
                # The owner has just chosen between competing definitions. Telling them the
                # measure "has one agreed definition" contradicts the question they were asked
                # one turn earlier, and hides that the figure depends on their choice.
                sentence = f"This is the definition of {subject} you chose"
            else:
                sentence = f"{subject.capitalize()} has one agreed definition for this question"
            sentence += (", and the result was checked against the available source records."
                         if checked else ", taken from your own business records.")
            paragraphs.append(sentence)
            if chosen:
                paragraphs.append(
                    "The other definition remains available and would give a different figure; "
                    "ask again and pick it to see that one instead.")
        if period and not forecast_paragraphs:
            paragraphs.append(
                f"The requested period was {period}, and the figure uses the evidence recorded "
                f"for that period.")
        if trust == "DISCLOSE":
            for a in (getattr(result, "answers", ()) or ()):
                caveat = _clean(getattr(a, "caveat", "") or "")
                if caveat:
                    paragraphs.append(caveat)
                    break

    elif trust == "NOT_DETERMINABLE" or not trust:
        heading = "Why I can't answer this"
        plan = getattr(result, "plan", None)
        reason = _clean(getattr(plan, "not_determinable_reason", "") or "") if plan else ""
        if not reason:
            # The answer's own stated reason, before any context was appended to it. Falling
            # straight through to `text` pulled the "latest recorded occupancy: 195" line into
            # the Why panel, restating the answer directly above it and putting a historical
            # figure inside an explanation of why no figure could be given.
            reason = _clean(getattr(result, "not_determinable_reason", "") or "")
        if not reason:
            # The answer body, but ONLY when it is a single statement. A multi-section workflow
            # draft -- headings, bullets, figures -- is the answer, and repeating it here under
            # "why" presents the same numbers a second time as though they were the reason for
            # themselves. A workflow that reaches this point without a structured projection
            # yields nothing rather than its own text.
            body = getattr(result, "text", "") or ""
            if "\n\n" not in body.strip() and "•" not in body:
                reason = _clean(body)
        if not reason:
            return {}
        extra = _forecast_refusal_reason(result) + _stated_limitations(result, reason)
        # The refusal sentence is often the answer's own opening line. Repeated here it is the
        # answer explaining itself, so it is kept only when nothing else can carry the reason.
        body = _clean(getattr(result, "text", "") or "")
        if not (extra and reason and reason in body):
            paragraphs.append(reason)
        paragraphs.extend(extra)

    else:
        return {}

    if change is not None and getattr(change, "current_is_partial", False):
        from engine.change_detection import EXPORT_SNAPSHOT_DATE
        from engine import owner_presentation as op
        asked = op._month_name(getattr(change, "requested_current", ""))
        paragraphs.append(
            f"{asked} is also incomplete in this export: the records stop at "
            f"{EXPORT_SNAPSHOT_DATE}.")

    cleaned = [p for p in (_clean(x) for x in paragraphs) if p]
    if not cleaned:
        return {}
    return {"heading": heading, "paragraphs": cleaned}


def render_owner_projection(projection):
    """The projection as plain text. Empty string when nothing can be said."""
    if not projection:
        return ""
    lines = [projection.get("heading", "Why this answer"), ""]
    lines.extend(projection.get("paragraphs", ()))
    return "\n".join(lines).strip()
